const USER_ROLES = Object.freeze({
  SUPERADMIN: 'SUPERADMIN',
  AUDITOR: 'AUDITOR',
  APPROVER: 'APPROVER',
  RECEPTIONIST: 'RECEPTIONIST',
  STUDENT: 'STUDENT',
});

const CREATABLE_ROLES_BY_SUPERADMIN = [
  USER_ROLES.AUDITOR,
  USER_ROLES.APPROVER,
  USER_ROLES.RECEPTIONIST,
  USER_ROLES.STUDENT,
];

const USER_STATUS = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
};

module.exports = {
  USER_ROLES,
  CREATABLE_ROLES_BY_SUPERADMIN,
  USER_STATUS
};
